server:
  port: 8001
  servlet:
    context-path: /provider
spring:
  application:
    name: consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
management:
  health:
    cassandra:
      enabled: false