server:
  port: 1000
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway-application
  cloud:
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: github # 路由的唯一标识
          uri: http://www.github.com # 路由指向的目标 URI，即请求最终被转发的目的地
          predicates:
            - Path=/github
          filters: # 过滤器，对请求进行拦截，实现自定义的功能
            - StripPrefix=1
        - id: gitee
          uri: http://www.gitee.com
          predicates:
            - Path=/gitee
          filters:
            - StripPrefix=1
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu
          filters:
            - StripPrefix=1
        - id: oschina # 路由的编号
          uri: https://www.oschina.net # 路由的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/oschina
          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
            - StripPrefix=1