server:
  port: 9001
  servlet:
    context-path: /consumer
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
management:
  health:
    cassandra:
      enabled: false